[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pythonproject3"
version = "0.1.0"
description = "Pdf Convertor"
authors = [{ name = "Your Name", email = "sujit56@example.com" }]
dependencies = []
